version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/node:18
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - mongo
    networks:
      - devnet

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - devnet

volumes:
  mongodb-data:

networks:
  devnet: